// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/nested-extension-lite.proto

package protobuf_unittest;

public final class NestedExtensionLite {
  private NestedExtensionLite() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite.recursiveExtensionLite);
  }
  public static final class MyNestedExtensionLite extends
      com.google.protobuf.GeneratedMessageLite {
    // Use MyNestedExtensionLite.newBuilder() to construct.
    private MyNestedExtensionLite() {
      initFields();
    }
    private MyNestedExtensionLite(boolean noInit) {}
    
    private static final MyNestedExtensionLite defaultInstance;
    public static MyNestedExtensionLite getDefaultInstance() {
      return defaultInstance;
    }
    
    public MyNestedExtensionLite getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final int RECURSIVEEXTENSIONLITE_FIELD_NUMBER = 3;
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended,
        protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended> recursiveExtensionLite =
          com.google.protobuf.GeneratedMessageLite
            .newGeneratedExtension();
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    public static protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite, Builder> {
      private protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite result;
      
      // Construct using protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite();
        return builder;
      }
      
      protected protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite getDefaultInstanceForType() {
        return protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite other) {
        if (other == protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite.getDefaultInstance()) return this;
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:protobuf_unittest.MyNestedExtensionLite)
    }
    
    static {
      defaultInstance = new MyNestedExtensionLite(true);
      protobuf_unittest.NestedExtensionLite.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf_unittest.MyNestedExtensionLite)
  }
  
  
  static {
    protobuf_unittest.NestedExtensionLite.MyNestedExtensionLite.recursiveExtensionLite.internalInitSingular(
        protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended.getDefaultInstance(),
        protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended.getDefaultInstance(),
        protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended.getDefaultInstance(),
        null,
        3,
        com.google.protobuf.WireFormat.FieldType.MESSAGE);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
