// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/nested-extension.proto

package protobuf_unittest;

public final class NestedExtension {
  private NestedExtension() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(protobuf_unittest.NestedExtension.MyNestedExtension.recursiveExtension);
  }
  public static final class MyNestedExtension extends
      com.google.protobuf.GeneratedMessage {
    // Use MyNestedExtension.newBuilder() to construct.
    private MyNestedExtension() {
      initFields();
    }
    private MyNestedExtension(boolean noInit) {}
    
    private static final MyNestedExtension defaultInstance;
    public static MyNestedExtension getDefaultInstance() {
      return defaultInstance;
    }
    
    public MyNestedExtension getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf_unittest.NestedExtension.internal_static_protobuf_unittest_MyNestedExtension_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf_unittest.NestedExtension.internal_static_protobuf_unittest_MyNestedExtension_fieldAccessorTable;
    }
    
    public static final int RECURSIVEEXTENSION_FIELD_NUMBER = 2;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        protobuf_unittest.NonNestedExtension.MessageToBeExtended,
        protobuf_unittest.NonNestedExtension.MessageToBeExtended> recursiveExtension =
          com.google.protobuf.GeneratedMessage
            .newGeneratedExtension();
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static protobuf_unittest.NestedExtension.MyNestedExtension parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NestedExtension.MyNestedExtension parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NestedExtension.MyNestedExtension parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NestedExtension.MyNestedExtension parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NestedExtension.MyNestedExtension parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NestedExtension.MyNestedExtension parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NestedExtension.MyNestedExtension parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NestedExtension.MyNestedExtension parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NestedExtension.MyNestedExtension parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NestedExtension.MyNestedExtension parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf_unittest.NestedExtension.MyNestedExtension prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private protobuf_unittest.NestedExtension.MyNestedExtension result;
      
      // Construct using protobuf_unittest.NestedExtension.MyNestedExtension.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new protobuf_unittest.NestedExtension.MyNestedExtension();
        return builder;
      }
      
      protected protobuf_unittest.NestedExtension.MyNestedExtension internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new protobuf_unittest.NestedExtension.MyNestedExtension();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf_unittest.NestedExtension.MyNestedExtension.getDescriptor();
      }
      
      public protobuf_unittest.NestedExtension.MyNestedExtension getDefaultInstanceForType() {
        return protobuf_unittest.NestedExtension.MyNestedExtension.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public protobuf_unittest.NestedExtension.MyNestedExtension build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private protobuf_unittest.NestedExtension.MyNestedExtension buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public protobuf_unittest.NestedExtension.MyNestedExtension buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        protobuf_unittest.NestedExtension.MyNestedExtension returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf_unittest.NestedExtension.MyNestedExtension) {
          return mergeFrom((protobuf_unittest.NestedExtension.MyNestedExtension)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf_unittest.NestedExtension.MyNestedExtension other) {
        if (other == protobuf_unittest.NestedExtension.MyNestedExtension.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:protobuf_unittest.MyNestedExtension)
    }
    
    static {
      defaultInstance = new MyNestedExtension(true);
      protobuf_unittest.NestedExtension.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf_unittest.MyNestedExtension)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_unittest_MyNestedExtension_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_unittest_MyNestedExtension_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/test/resources/nested-extension.pr" +
      "oto\022\021protobuf_unittest\032-src/test/resourc" +
      "es/non-nested-extension.proto\"\177\n\021MyNeste" +
      "dExtension2j\n\022recursiveExtension\022&.proto" +
      "buf_unittest.MessageToBeExtended\030\002 \001(\0132&" +
      ".protobuf_unittest.MessageToBeExtended"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_unittest_MyNestedExtension_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_unittest_MyNestedExtension_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_unittest_MyNestedExtension_descriptor,
              new java.lang.String[] { },
              protobuf_unittest.NestedExtension.MyNestedExtension.class,
              protobuf_unittest.NestedExtension.MyNestedExtension.Builder.class);
          protobuf_unittest.NestedExtension.MyNestedExtension.recursiveExtension.internalInit(
              protobuf_unittest.NestedExtension.MyNestedExtension.getDescriptor().getExtensions().get(0),
              protobuf_unittest.NonNestedExtension.MessageToBeExtended.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf_unittest.NonNestedExtension.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
