// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/non-nested-extension-lite.proto

package protobuf_unittest;

public final class NonNestedExtensionLite {
  private NonNestedExtensionLite() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(protobuf_unittest.NonNestedExtensionLite.nonNestedExtensionLite);
  }
  public static final class MessageLiteToBeExtended extends
      com.google.protobuf.GeneratedMessageLite.ExtendableMessage<
        MessageLiteToBeExtended> {
    // Use MessageLiteToBeExtended.newBuilder() to construct.
    private MessageLiteToBeExtended() {
      initFields();
    }
    private MessageLiteToBeExtended(boolean noInit) {}
    
    private static final MessageLiteToBeExtended defaultInstance;
    public static MessageLiteToBeExtended getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageLiteToBeExtended getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!extensionsAreInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessageLite.ExtendableMessage
        .ExtensionWriter extensionWriter = newExtensionWriter();
      extensionWriter.writeUntil(536870912, output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += extensionsSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.ExtendableBuilder<
          protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended, Builder> {
      private protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended result;
      
      // Construct using protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended();
        return builder;
      }
      
      protected protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended getDefaultInstanceForType() {
        return protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended other) {
        if (other == protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended.getDefaultInstance()) return this;
        this.mergeExtensionFields(other);
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:protobuf_unittest.MessageLiteToBeExtended)
    }
    
    static {
      defaultInstance = new MessageLiteToBeExtended(true);
      protobuf_unittest.NonNestedExtensionLite.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf_unittest.MessageLiteToBeExtended)
  }
  
  public static final class MyNonNestedExtensionLite extends
      com.google.protobuf.GeneratedMessageLite {
    // Use MyNonNestedExtensionLite.newBuilder() to construct.
    private MyNonNestedExtensionLite() {
      initFields();
    }
    private MyNonNestedExtensionLite(boolean noInit) {}
    
    private static final MyNonNestedExtensionLite defaultInstance;
    public static MyNonNestedExtensionLite getDefaultInstance() {
      return defaultInstance;
    }
    
    public MyNonNestedExtensionLite getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    public static protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite, Builder> {
      private protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite result;
      
      // Construct using protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite();
        return builder;
      }
      
      protected protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite getDefaultInstanceForType() {
        return protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite other) {
        if (other == protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite.getDefaultInstance()) return this;
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:protobuf_unittest.MyNonNestedExtensionLite)
    }
    
    static {
      defaultInstance = new MyNonNestedExtensionLite(true);
      protobuf_unittest.NonNestedExtensionLite.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf_unittest.MyNonNestedExtensionLite)
  }
  
  public static final int NONNESTEDEXTENSIONLITE_FIELD_NUMBER = 1;
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended,
      protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite> nonNestedExtensionLite =
        com.google.protobuf.GeneratedMessageLite
          .newGeneratedExtension();
  
  static {
    protobuf_unittest.NonNestedExtensionLite.nonNestedExtensionLite.internalInitSingular(
        protobuf_unittest.NonNestedExtensionLite.MessageLiteToBeExtended.getDefaultInstance(),
        protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite.getDefaultInstance(),
        protobuf_unittest.NonNestedExtensionLite.MyNonNestedExtensionLite.getDefaultInstance(),
        null,
        1,
        com.google.protobuf.WireFormat.FieldType.MESSAGE);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
