// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/non-nested-extension.proto

package protobuf_unittest;

public final class NonNestedExtension {
  private NonNestedExtension() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(protobuf_unittest.NonNestedExtension.nonNestedExtension);
  }
  public static final class MessageToBeExtended extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        MessageToBeExtended> {
    // Use MessageToBeExtended.newBuilder() to construct.
    private MessageToBeExtended() {
      initFields();
    }
    private MessageToBeExtended(boolean noInit) {}
    
    private static final MessageToBeExtended defaultInstance;
    public static MessageToBeExtended getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageToBeExtended getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf_unittest.NonNestedExtension.internal_static_protobuf_unittest_MessageToBeExtended_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf_unittest.NonNestedExtension.internal_static_protobuf_unittest_MessageToBeExtended_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!extensionsAreInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage.ExtendableMessage
        .ExtensionWriter extensionWriter = newExtensionWriter();
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static protobuf_unittest.NonNestedExtension.MessageToBeExtended parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MessageToBeExtended parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MessageToBeExtended parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MessageToBeExtended parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MessageToBeExtended parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MessageToBeExtended parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MessageToBeExtended parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NonNestedExtension.MessageToBeExtended parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NonNestedExtension.MessageToBeExtended parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MessageToBeExtended parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf_unittest.NonNestedExtension.MessageToBeExtended prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          protobuf_unittest.NonNestedExtension.MessageToBeExtended, Builder> {
      private protobuf_unittest.NonNestedExtension.MessageToBeExtended result;
      
      // Construct using protobuf_unittest.NonNestedExtension.MessageToBeExtended.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new protobuf_unittest.NonNestedExtension.MessageToBeExtended();
        return builder;
      }
      
      protected protobuf_unittest.NonNestedExtension.MessageToBeExtended internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new protobuf_unittest.NonNestedExtension.MessageToBeExtended();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf_unittest.NonNestedExtension.MessageToBeExtended.getDescriptor();
      }
      
      public protobuf_unittest.NonNestedExtension.MessageToBeExtended getDefaultInstanceForType() {
        return protobuf_unittest.NonNestedExtension.MessageToBeExtended.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public protobuf_unittest.NonNestedExtension.MessageToBeExtended build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private protobuf_unittest.NonNestedExtension.MessageToBeExtended buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public protobuf_unittest.NonNestedExtension.MessageToBeExtended buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        protobuf_unittest.NonNestedExtension.MessageToBeExtended returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf_unittest.NonNestedExtension.MessageToBeExtended) {
          return mergeFrom((protobuf_unittest.NonNestedExtension.MessageToBeExtended)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf_unittest.NonNestedExtension.MessageToBeExtended other) {
        if (other == protobuf_unittest.NonNestedExtension.MessageToBeExtended.getDefaultInstance()) return this;
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:protobuf_unittest.MessageToBeExtended)
    }
    
    static {
      defaultInstance = new MessageToBeExtended(true);
      protobuf_unittest.NonNestedExtension.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf_unittest.MessageToBeExtended)
  }
  
  public static final class MyNonNestedExtension extends
      com.google.protobuf.GeneratedMessage {
    // Use MyNonNestedExtension.newBuilder() to construct.
    private MyNonNestedExtension() {
      initFields();
    }
    private MyNonNestedExtension(boolean noInit) {}
    
    private static final MyNonNestedExtension defaultInstance;
    public static MyNonNestedExtension getDefaultInstance() {
      return defaultInstance;
    }
    
    public MyNonNestedExtension getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf_unittest.NonNestedExtension.internal_static_protobuf_unittest_MyNonNestedExtension_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf_unittest.NonNestedExtension.internal_static_protobuf_unittest_MyNonNestedExtension_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static protobuf_unittest.NonNestedExtension.MyNonNestedExtension parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MyNonNestedExtension parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MyNonNestedExtension parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MyNonNestedExtension parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MyNonNestedExtension parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MyNonNestedExtension parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MyNonNestedExtension parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NonNestedExtension.MyNonNestedExtension parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.NonNestedExtension.MyNonNestedExtension parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.NonNestedExtension.MyNonNestedExtension parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf_unittest.NonNestedExtension.MyNonNestedExtension prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private protobuf_unittest.NonNestedExtension.MyNonNestedExtension result;
      
      // Construct using protobuf_unittest.NonNestedExtension.MyNonNestedExtension.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new protobuf_unittest.NonNestedExtension.MyNonNestedExtension();
        return builder;
      }
      
      protected protobuf_unittest.NonNestedExtension.MyNonNestedExtension internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new protobuf_unittest.NonNestedExtension.MyNonNestedExtension();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf_unittest.NonNestedExtension.MyNonNestedExtension.getDescriptor();
      }
      
      public protobuf_unittest.NonNestedExtension.MyNonNestedExtension getDefaultInstanceForType() {
        return protobuf_unittest.NonNestedExtension.MyNonNestedExtension.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public protobuf_unittest.NonNestedExtension.MyNonNestedExtension build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private protobuf_unittest.NonNestedExtension.MyNonNestedExtension buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public protobuf_unittest.NonNestedExtension.MyNonNestedExtension buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        protobuf_unittest.NonNestedExtension.MyNonNestedExtension returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf_unittest.NonNestedExtension.MyNonNestedExtension) {
          return mergeFrom((protobuf_unittest.NonNestedExtension.MyNonNestedExtension)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf_unittest.NonNestedExtension.MyNonNestedExtension other) {
        if (other == protobuf_unittest.NonNestedExtension.MyNonNestedExtension.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:protobuf_unittest.MyNonNestedExtension)
    }
    
    static {
      defaultInstance = new MyNonNestedExtension(true);
      protobuf_unittest.NonNestedExtension.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf_unittest.MyNonNestedExtension)
  }
  
  public static final int NONNESTEDEXTENSION_FIELD_NUMBER = 1;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      protobuf_unittest.NonNestedExtension.MessageToBeExtended,
      protobuf_unittest.NonNestedExtension.MyNonNestedExtension> nonNestedExtension =
        com.google.protobuf.GeneratedMessage
          .newGeneratedExtension();
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_unittest_MessageToBeExtended_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_unittest_MessageToBeExtended_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_unittest_MyNonNestedExtension_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_unittest_MyNonNestedExtension_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/test/resources/non-nested-extensio" +
      "n.proto\022\021protobuf_unittest\"\037\n\023MessageToB" +
      "eExtended*\010\010\001\020\200\200\200\200\002\"\026\n\024MyNonNestedExtens" +
      "ion:k\n\022nonNestedExtension\022&.protobuf_uni" +
      "ttest.MessageToBeExtended\030\001 \001(\0132\'.protob" +
      "uf_unittest.MyNonNestedExtension"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_unittest_MessageToBeExtended_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_unittest_MessageToBeExtended_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_unittest_MessageToBeExtended_descriptor,
              new java.lang.String[] { },
              protobuf_unittest.NonNestedExtension.MessageToBeExtended.class,
              protobuf_unittest.NonNestedExtension.MessageToBeExtended.Builder.class);
          internal_static_protobuf_unittest_MyNonNestedExtension_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_unittest_MyNonNestedExtension_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_unittest_MyNonNestedExtension_descriptor,
              new java.lang.String[] { },
              protobuf_unittest.NonNestedExtension.MyNonNestedExtension.class,
              protobuf_unittest.NonNestedExtension.MyNonNestedExtension.Builder.class);
          protobuf_unittest.NonNestedExtension.nonNestedExtension.internalInit(
              protobuf_unittest.NonNestedExtension.getDescriptor().getExtensions().get(0),
              protobuf_unittest.NonNestedExtension.MyNonNestedExtension.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
