// Generated by the protocol buffer compiler.  DO NOT EDIT!

package protobuf_unittest;

public  final class Wheel extends
    com.google.protobuf.GeneratedMessage {
  // Use Wheel.newBuilder() to construct.
  private Wheel() {
    initFields();
  }
  private Wheel(boolean noInit) {}
  
  private static final Wheel defaultInstance;
  public static Wheel getDefaultInstance() {
    return defaultInstance;
  }
  
  public Wheel getDefaultInstanceForType() {
    return defaultInstance;
  }
  
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf_unittest.NestedBuilders.internal_static_protobuf_unittest_Wheel_descriptor;
  }
  
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf_unittest.NestedBuilders.internal_static_protobuf_unittest_Wheel_fieldAccessorTable;
  }
  
  // optional int32 radius = 1;
  public static final int RADIUS_FIELD_NUMBER = 1;
  private boolean hasRadius;
  private int radius_ = 0;
  public boolean hasRadius() { return hasRadius; }
  public int getRadius() { return radius_; }
  
  // optional int32 width = 2;
  public static final int WIDTH_FIELD_NUMBER = 2;
  private boolean hasWidth;
  private int width_ = 0;
  public boolean hasWidth() { return hasWidth; }
  public int getWidth() { return width_; }
  
  private void initFields() {
  }
  public final boolean isInitialized() {
    return true;
  }
  
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (hasRadius()) {
      output.writeInt32(1, getRadius());
    }
    if (hasWidth()) {
      output.writeInt32(2, getWidth());
    }
    getUnknownFields().writeTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
  
    size = 0;
    if (hasRadius()) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, getRadius());
    }
    if (hasWidth()) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, getWidth());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }
  
  public static protobuf_unittest.Wheel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static protobuf_unittest.Wheel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static protobuf_unittest.Wheel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static protobuf_unittest.Wheel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static protobuf_unittest.Wheel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static protobuf_unittest.Wheel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  public static protobuf_unittest.Wheel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static protobuf_unittest.Wheel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static protobuf_unittest.Wheel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static protobuf_unittest.Wheel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  
  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(protobuf_unittest.Wheel prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }
  
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> {
    private protobuf_unittest.Wheel result;
    
    // Construct using protobuf_unittest.Wheel.newBuilder()
    private Builder() {}
    
    private static Builder create() {
      Builder builder = new Builder();
      builder.result = new protobuf_unittest.Wheel();
      return builder;
    }
    
    protected protobuf_unittest.Wheel internalGetResult() {
      return result;
    }
    
    public Builder clear() {
      if (result == null) {
        throw new IllegalStateException(
          "Cannot call clear() after build().");
      }
      result = new protobuf_unittest.Wheel();
      return this;
    }
    
    public Builder clone() {
      return create().mergeFrom(result);
    }
    
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf_unittest.Wheel.getDescriptor();
    }
    
    public protobuf_unittest.Wheel getDefaultInstanceForType() {
      return protobuf_unittest.Wheel.getDefaultInstance();
    }
    
    public boolean isInitialized() {
      return result.isInitialized();
    }
    public protobuf_unittest.Wheel build() {
      if (result != null && !isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return buildPartial();
    }
    
    private protobuf_unittest.Wheel buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
      if (!isInitialized()) {
        throw newUninitializedMessageException(
          result).asInvalidProtocolBufferException();
      }
      return buildPartial();
    }
    
    public protobuf_unittest.Wheel buildPartial() {
      if (result == null) {
        throw new IllegalStateException(
          "build() has already been called on this Builder.");
      }
      protobuf_unittest.Wheel returnMe = result;
      result = null;
      return returnMe;
    }
    
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf_unittest.Wheel) {
        return mergeFrom((protobuf_unittest.Wheel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }
    
    public Builder mergeFrom(protobuf_unittest.Wheel other) {
      if (other == protobuf_unittest.Wheel.getDefaultInstance()) return this;
      if (other.hasRadius()) {
        setRadius(other.getRadius());
      }
      if (other.hasWidth()) {
        setWidth(other.getWidth());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }
    
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder(
          this.getUnknownFields());
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            this.setUnknownFields(unknownFields.build());
            return this;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              this.setUnknownFields(unknownFields.build());
              return this;
            }
            break;
          }
          case 8: {
            setRadius(input.readInt32());
            break;
          }
          case 16: {
            setWidth(input.readInt32());
            break;
          }
        }
      }
    }
    
    
    // optional int32 radius = 1;
    public boolean hasRadius() {
      return result.hasRadius();
    }
    public int getRadius() {
      return result.getRadius();
    }
    public Builder setRadius(int value) {
      result.hasRadius = true;
      result.radius_ = value;
      return this;
    }
    public Builder clearRadius() {
      result.hasRadius = false;
      result.radius_ = 0;
      return this;
    }
    
    // optional int32 width = 2;
    public boolean hasWidth() {
      return result.hasWidth();
    }
    public int getWidth() {
      return result.getWidth();
    }
    public Builder setWidth(int value) {
      result.hasWidth = true;
      result.width_ = value;
      return this;
    }
    public Builder clearWidth() {
      result.hasWidth = false;
      result.width_ = 0;
      return this;
    }
    
    // @@protoc_insertion_point(builder_scope:protobuf_unittest.Wheel)
  }
  
  static {
    defaultInstance = new Wheel(true);
    protobuf_unittest.NestedBuilders.internalForceInit();
    defaultInstance.initFields();
  }
  
  // @@protoc_insertion_point(class_scope:protobuf_unittest.Wheel)
}

