// Generated by the protocol buffer gcless compiler.  DO NOT EDIT!
package com.x.protobuf;

public final class Bug15 {
private Bug15() {}
public enum MsgType {
INC_TC_MSG(0),
;
public static MsgType valueOf(int value) {
switch (value) {
case 0: return INC_TC_MSG;
default: return null;
}
}
private MsgType(int value) {
this.value = value;
}
private int value;
public int getValue() {
return value;
}
}

}

