// Generated by the protocol buffer gcless compiler.  DO NOT EDIT!
package com.x.protobuf;

import java.io.IOException;
public final class Bug11 {
private Bug11() {}
public static class A {
private java.util.List<com.x.protobuf.Bug11.B> entry;
private boolean hasEntry;
public boolean hasEntry() {
return hasEntry;
}
public java.util.List<com.x.protobuf.Bug11.B> getEntry() {
return entry;
}
public void setEntry(java.util.List<com.x.protobuf.Bug11.B> Entry) {
this.entry = Entry;
this.hasEntry = true;
}
private int entry2;
private boolean hasEntry2;
public boolean hasEntry2() {
return hasEntry2;
}
public int getEntry2() {
return entry2;
}
public void setEntry2(int Entry2) {
this.entry2 = Entry2;
this.hasEntry2 = true;
}
}
public static class ASerializer {
public static byte[] serialize(com.x.protobuf.Bug11.A message) {
try {
int totalSize = 0;
byte[] entryBuffer = null;
if (message.hasEntry()) {
java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
for( int i=0;i<message.getEntry().size();i++) {
byte[] curMessageData = com.x.protobuf.Bug11.BSerializer.serialize(message.getEntry().get(i));
ProtobufOutputStream.writeMessageTag(32904, baos);
ProtobufOutputStream.writeRawVarint32(curMessageData.length, baos);
baos.write(curMessageData);
}
entryBuffer = baos.toByteArray();
totalSize += entryBuffer.length;
}
if (message.hasEntry2()) {
totalSize += ProtobufOutputStream.computeInt32Size(32902, message.getEntry2());
}
final byte[] result = new byte[totalSize];
int position = 0;
if (message.hasEntry()) {
position = ProtobufOutputStream.writeRawBytes(entryBuffer, result, position);
}
if (message.hasEntry2()) {
position = ProtobufOutputStream.writeInt32(32902, message.getEntry2(), result, position);
}
ProtobufOutputStream.checkNoSpaceLeft(result, position);
return result;
} catch (Exception e) {
throw new RuntimeException(e);
}
}
public static void serialize(com.x.protobuf.Bug11.A message, java.io.OutputStream os) {
try {
if (message.hasEntry()) {
for( int i=0;i<message.getEntry().size();i++) {
byte[] curMessageData = com.x.protobuf.Bug11.BSerializer.serialize(message.getEntry().get(i));
ProtobufOutputStream.writeMessageTag(32904, os);
ProtobufOutputStream.writeRawVarint32(curMessageData.length, os);
os.write(curMessageData);
}
}
if (message.hasEntry2()) {
ProtobufOutputStream.writeInt32(32902, message.getEntry2(), os);
}
} catch (IOException e) {
throw new RuntimeException("Serializing to a byte array threw an IOException (should never happen).", e);
}
}
public static com.x.protobuf.Bug11.A parseFrom(byte[] data) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
return parseFrom(data, cursor);
}
public static com.x.protobuf.Bug11.A parseFrom(byte[] data, int offset, int length) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
return parseFrom(data, cursor);
}
public static com.x.protobuf.Bug11.A parseFrom(byte[] data, CurrentCursor cursor) throws java.io.IOException {
com.x.protobuf.Bug11.A message = new com.x.protobuf.Bug11.A();
while(true) {
if (ProtobufInputStream.isAtEnd(data, cursor)) {
return message;
}
int varint = ProtobufInputStream.readRawVarint32(data, cursor);
int tag = ProtobufInputStream.getTagFieldNumber(varint);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(varint, data, cursor);
 break;
case 32904: 
if( message.getEntry() == null || message.getEntry().isEmpty()) {
message.setEntry(new java.util.ArrayList<com.x.protobuf.Bug11.B>());
}
int lengthEntry = ProtobufInputStream.readRawVarint32(data,cursor);
message.getEntry().add(com.x.protobuf.Bug11.BSerializer.parseFrom(data, cursor.getCurrentPosition(), lengthEntry));
cursor.addToPosition(lengthEntry);
break;
case 32902: 
message.setEntry2(ProtobufInputStream.readInt32(data,cursor));
break;
}
}
}
public static com.x.protobuf.Bug11.A parseFrom(java.io.InputStream is) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
return parseFrom(is, cursor);
}
public static com.x.protobuf.Bug11.A parseFrom(java.io.InputStream is, int offset, int length) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
return parseFrom(is, cursor);
}
public static com.x.protobuf.Bug11.A parseFrom(java.io.InputStream is, CurrentCursor cursor) throws java.io.IOException {
com.x.protobuf.Bug11.A message = new com.x.protobuf.Bug11.A();
while(true) {
if( cursor.getCurrentPosition() == cursor.getProcessUpToPosition() ) {
return message;
}
int varint = ProtobufInputStream.readRawVarint32(is, cursor);
int tag = ProtobufInputStream.getTagFieldNumber(varint);
if (ProtobufInputStream.isAtEnd(cursor)) {
return message;
}
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(varint, is, cursor);
 break;case 32904: 
if( message.getEntry() == null || message.getEntry().isEmpty()) {
message.setEntry(new java.util.ArrayList<com.x.protobuf.Bug11.B>());
}
int lengthEntry = ProtobufInputStream.readRawVarint32(is,cursor);
message.getEntry().add(com.x.protobuf.Bug11.BSerializer.parseFrom(is, cursor.getCurrentPosition(), lengthEntry));
cursor.addToPosition(lengthEntry);
break;
case 32902: 
message.setEntry2(ProtobufInputStream.readInt32(is,cursor));
break;
}
}
}
}
public static class B {
private String val;
private boolean hasVal;
public boolean hasVal() {
return hasVal;
}
public String getVal() {
return val;
}
public void setVal(String Val) {
this.val = Val;
this.hasVal = true;
}
private com.x.protobuf.Bug11.C cval;
private boolean hasCval;
public boolean hasCval() {
return hasCval;
}
public com.x.protobuf.Bug11.C getCval() {
return cval;
}
public void setCval(com.x.protobuf.Bug11.C Cval) {
this.cval = Cval;
this.hasCval = true;
}
private java.util.List<com.x.protobuf.Bug11.B.Result> result;
private boolean hasResult;
public boolean hasResult() {
return hasResult;
}
public java.util.List<com.x.protobuf.Bug11.B.Result> getResult() {
return result;
}
public void setResult(java.util.List<com.x.protobuf.Bug11.B.Result> Result) {
this.result = Result;
this.hasResult = true;
}
public static class Result {
private String url;
private boolean hasUrl;
public boolean hasUrl() {
return hasUrl;
}
public String getUrl() {
return url;
}
public void setUrl(String Url) {
this.url = Url;
this.hasUrl = true;
}
private String title;
private boolean hasTitle;
public boolean hasTitle() {
return hasTitle;
}
public String getTitle() {
return title;
}
public void setTitle(String Title) {
this.title = Title;
this.hasTitle = true;
}
private java.util.List<String> snippets;
private boolean hasSnippets;
public boolean hasSnippets() {
return hasSnippets;
}
public java.util.List<String> getSnippets() {
return snippets;
}
public void setSnippets(java.util.List<String> Snippets) {
this.snippets = Snippets;
this.hasSnippets = true;
}
}
public static class ResultSerializer {
public static byte[] serialize(com.x.protobuf.Bug11.B.Result message) {
try {
assertInitialized(message);
int totalSize = 0;
byte[] urlBuffer = null;
if (message.hasUrl()) {
urlBuffer = message.getUrl().getBytes("UTF-8");
totalSize += urlBuffer.length;
totalSize += ProtobufOutputStream.computeTagSize(2);
totalSize += ProtobufOutputStream.computeRawVarint32Size(urlBuffer.length);
}
byte[] titleBuffer = null;
if (message.hasTitle()) {
titleBuffer = message.getTitle().getBytes("UTF-8");
totalSize += titleBuffer.length;
totalSize += ProtobufOutputStream.computeTagSize(3);
totalSize += ProtobufOutputStream.computeRawVarint32Size(titleBuffer.length);
}
byte[] snippetsBuffer = null;
if (message.hasSnippets()) {
java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
for( int i=0;i<message.getSnippets().size();i++) {
ProtobufOutputStream.writeString(4, message.getSnippets().get(i), baos);
}
snippetsBuffer = baos.toByteArray();
totalSize += snippetsBuffer.length;
}
final byte[] result = new byte[totalSize];
int position = 0;
if (message.hasUrl()) {
position = ProtobufOutputStream.writeString(2,urlBuffer, result, position);
}
if (message.hasTitle()) {
position = ProtobufOutputStream.writeString(3,titleBuffer, result, position);
}
if (message.hasSnippets()) {
position = ProtobufOutputStream.writeRawBytes(snippetsBuffer, result, position);
}
ProtobufOutputStream.checkNoSpaceLeft(result, position);
return result;
} catch (Exception e) {
throw new RuntimeException(e);
}
}
public static void serialize(com.x.protobuf.Bug11.B.Result message, java.io.OutputStream os) {
try {
assertInitialized(message);
if (message.hasUrl()) {
ProtobufOutputStream.writeString(2, message.getUrl(), os);
}
if (message.hasTitle()) {
ProtobufOutputStream.writeString(3, message.getTitle(), os);
}
if (message.hasSnippets()) {
for( int i=0;i<message.getSnippets().size();i++) {
ProtobufOutputStream.writeString(4, message.getSnippets().get(i), os);
}
}
} catch (IOException e) {
throw new RuntimeException("Serializing to a byte array threw an IOException (should never happen).", e);
}
}
public static com.x.protobuf.Bug11.B.Result parseFrom(byte[] data) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
return parseFrom(data, cursor);
}
public static com.x.protobuf.Bug11.B.Result parseFrom(byte[] data, int offset, int length) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
return parseFrom(data, cursor);
}
public static com.x.protobuf.Bug11.B.Result parseFrom(byte[] data, CurrentCursor cursor) throws java.io.IOException {
com.x.protobuf.Bug11.B.Result message = new com.x.protobuf.Bug11.B.Result();
while(true) {
if (ProtobufInputStream.isAtEnd(data, cursor)) {
return message;
}
int varint = ProtobufInputStream.readRawVarint32(data, cursor);
int tag = ProtobufInputStream.getTagFieldNumber(varint);
int wireType = varint & ProtobufInputStream.TAG_TYPE_MASK;
if (wireType == ProtobufInputStream.WIRETYPE_GROUP_END) {
return message;
}
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(varint, data, cursor);
 break;
case 2: 
message.setUrl(ProtobufInputStream.readString(data,cursor));
break;
case 3: 
message.setTitle(ProtobufInputStream.readString(data,cursor));
break;
case 4: 
if( message.getSnippets() == null || message.getSnippets().isEmpty()) {
message.setSnippets(new java.util.ArrayList<String>());
}
message.getSnippets().add(ProtobufInputStream.readString(data,cursor));
break;
}
}
}
public static com.x.protobuf.Bug11.B.Result parseFrom(java.io.InputStream is) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
return parseFrom(is, cursor);
}
public static com.x.protobuf.Bug11.B.Result parseFrom(java.io.InputStream is, int offset, int length) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
return parseFrom(is, cursor);
}
public static com.x.protobuf.Bug11.B.Result parseFrom(java.io.InputStream is, CurrentCursor cursor) throws java.io.IOException {
com.x.protobuf.Bug11.B.Result message = new com.x.protobuf.Bug11.B.Result();
while(true) {
if( cursor.getCurrentPosition() == cursor.getProcessUpToPosition() ) {
return message;
}
int varint = ProtobufInputStream.readRawVarint32(is, cursor);
int tag = ProtobufInputStream.getTagFieldNumber(varint);
if (ProtobufInputStream.isAtEnd(cursor)) {
return message;
}
int wireType = varint & ProtobufInputStream.TAG_TYPE_MASK;
if (wireType == ProtobufInputStream.WIRETYPE_GROUP_END) {
return message;
}
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(varint, is, cursor);
 break;case 2: 
message.setUrl(ProtobufInputStream.readString(is,cursor));
break;
case 3: 
message.setTitle(ProtobufInputStream.readString(is,cursor));
break;
case 4: 
if( message.getSnippets() == null || message.getSnippets().isEmpty()) {
message.setSnippets(new java.util.ArrayList<String>());
}
message.getSnippets().add(ProtobufInputStream.readString(is,cursor));
break;
}
}
}
private static void assertInitialized(com.x.protobuf.Bug11.B.Result message) {
if( !message.hasUrl()) {
throw new IllegalArgumentException("Required field not initialized: url");
}
}
}
}
public static class BSerializer {
public static byte[] serialize(com.x.protobuf.Bug11.B message) {
try {
int totalSize = 0;
byte[] valBuffer = null;
if (message.hasVal()) {
valBuffer = message.getVal().getBytes("UTF-8");
totalSize += valBuffer.length;
totalSize += ProtobufOutputStream.computeTagSize(1);
totalSize += ProtobufOutputStream.computeRawVarint32Size(valBuffer.length);
}
byte[] cvalBuffer = null;
if (message.hasCval()) {
cvalBuffer = com.x.protobuf.Bug11.CSerializer.serialize(message.getCval());
totalSize += ProtobufOutputStream.computeTagSize(2);
totalSize += ProtobufOutputStream.computeRawVarint32Size(cvalBuffer.length);
totalSize += cvalBuffer.length;
}
byte[] resultBuffer = null;
if (message.hasResult()) {
java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
for( int i=0;i<message.getResult().size();i++) {
byte[] curMessageData = com.x.protobuf.Bug11.B.ResultSerializer.serialize(message.getResult().get(i));
ProtobufOutputStream.writeTag(3, ProtobufInputStream.WIRETYPE_GROUP_START, baos);
baos.write(curMessageData);
ProtobufOutputStream.writeTag(3, ProtobufInputStream.WIRETYPE_GROUP_END, baos);
}
resultBuffer = baos.toByteArray();
totalSize += resultBuffer.length;
}
final byte[] result = new byte[totalSize];
int position = 0;
if (message.hasVal()) {
position = ProtobufOutputStream.writeString(1,valBuffer, result, position);
}
if (message.hasCval()) {
position = ProtobufOutputStream.writeBytes(2, cvalBuffer, result, position);
}
if (message.hasResult()) {
position = ProtobufOutputStream.writeRawBytes(resultBuffer, result, position);
}
ProtobufOutputStream.checkNoSpaceLeft(result, position);
return result;
} catch (Exception e) {
throw new RuntimeException(e);
}
}
public static void serialize(com.x.protobuf.Bug11.B message, java.io.OutputStream os) {
try {
if (message.hasVal()) {
ProtobufOutputStream.writeString(1, message.getVal(), os);
}
if (message.hasCval()) {
byte[] curMessageData = com.x.protobuf.Bug11.CSerializer.serialize(message.getCval());
ProtobufOutputStream.writeMessageTag(2, os);
ProtobufOutputStream.writeRawVarint32(curMessageData.length, os);
os.write(curMessageData);
}
if (message.hasResult()) {
for( int i=0;i<message.getResult().size();i++) {
ProtobufOutputStream.writeTag(3, ProtobufInputStream.WIRETYPE_GROUP_START, os);
os.write(com.x.protobuf.Bug11.B.ResultSerializer.serialize(message.getResult().get(i)));
ProtobufOutputStream.writeTag(3, ProtobufInputStream.WIRETYPE_GROUP_END, os);
}
}
} catch (IOException e) {
throw new RuntimeException("Serializing to a byte array threw an IOException (should never happen).", e);
}
}
public static com.x.protobuf.Bug11.B parseFrom(byte[] data) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
return parseFrom(data, cursor);
}
public static com.x.protobuf.Bug11.B parseFrom(byte[] data, int offset, int length) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
return parseFrom(data, cursor);
}
public static com.x.protobuf.Bug11.B parseFrom(byte[] data, CurrentCursor cursor) throws java.io.IOException {
com.x.protobuf.Bug11.B message = new com.x.protobuf.Bug11.B();
while(true) {
if (ProtobufInputStream.isAtEnd(data, cursor)) {
return message;
}
int varint = ProtobufInputStream.readRawVarint32(data, cursor);
int tag = ProtobufInputStream.getTagFieldNumber(varint);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(varint, data, cursor);
 break;
case 1: 
message.setVal(ProtobufInputStream.readString(data,cursor));
break;
case 2: 
int lengthCval = ProtobufInputStream.readRawVarint32(data,cursor);
message.setCval(com.x.protobuf.Bug11.CSerializer.parseFrom(data, cursor.getCurrentPosition(), lengthCval));
cursor.addToPosition(lengthCval);
break;
case 3: 
if( message.getResult() == null || message.getResult().isEmpty()) {
message.setResult(new java.util.ArrayList<com.x.protobuf.Bug11.B.Result>());
}
com.x.protobuf.Bug11.B.Result tempResult = com.x.protobuf.Bug11.B.ResultSerializer.parseFrom(data, cursor);
message.getResult().add(tempResult);
break;
}
}
}
public static com.x.protobuf.Bug11.B parseFrom(java.io.InputStream is) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
return parseFrom(is, cursor);
}
public static com.x.protobuf.Bug11.B parseFrom(java.io.InputStream is, int offset, int length) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
return parseFrom(is, cursor);
}
public static com.x.protobuf.Bug11.B parseFrom(java.io.InputStream is, CurrentCursor cursor) throws java.io.IOException {
com.x.protobuf.Bug11.B message = new com.x.protobuf.Bug11.B();
while(true) {
if( cursor.getCurrentPosition() == cursor.getProcessUpToPosition() ) {
return message;
}
int varint = ProtobufInputStream.readRawVarint32(is, cursor);
int tag = ProtobufInputStream.getTagFieldNumber(varint);
if (ProtobufInputStream.isAtEnd(cursor)) {
return message;
}
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(varint, is, cursor);
 break;case 1: 
message.setVal(ProtobufInputStream.readString(is,cursor));
break;
case 2: 
int lengthCval = ProtobufInputStream.readRawVarint32(is,cursor);
message.setCval(com.x.protobuf.Bug11.CSerializer.parseFrom(is, cursor.getCurrentPosition(), lengthCval));
cursor.addToPosition(lengthCval);
break;
case 3: 
if( message.getResult() == null || message.getResult().isEmpty()) {
message.setResult(new java.util.ArrayList<com.x.protobuf.Bug11.B.Result>());
}
com.x.protobuf.Bug11.B.Result tempResult = com.x.protobuf.Bug11.B.ResultSerializer.parseFrom(is, cursor);
message.getResult().add(tempResult);
break;
}
}
}
}
public static class C {
private String val;
private boolean hasVal;
public boolean hasVal() {
return hasVal;
}
public String getVal() {
return val;
}
public void setVal(String Val) {
this.val = Val;
this.hasVal = true;
}
}
public static class CSerializer {
public static byte[] serialize(com.x.protobuf.Bug11.C message) {
try {
int totalSize = 0;
byte[] valBuffer = null;
if (message.hasVal()) {
valBuffer = message.getVal().getBytes("UTF-8");
totalSize += valBuffer.length;
totalSize += ProtobufOutputStream.computeTagSize(1);
totalSize += ProtobufOutputStream.computeRawVarint32Size(valBuffer.length);
}
final byte[] result = new byte[totalSize];
int position = 0;
if (message.hasVal()) {
position = ProtobufOutputStream.writeString(1,valBuffer, result, position);
}
ProtobufOutputStream.checkNoSpaceLeft(result, position);
return result;
} catch (Exception e) {
throw new RuntimeException(e);
}
}
public static void serialize(com.x.protobuf.Bug11.C message, java.io.OutputStream os) {
try {
if (message.hasVal()) {
ProtobufOutputStream.writeString(1, message.getVal(), os);
}
} catch (IOException e) {
throw new RuntimeException("Serializing to a byte array threw an IOException (should never happen).", e);
}
}
public static com.x.protobuf.Bug11.C parseFrom(byte[] data) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
return parseFrom(data, cursor);
}
public static com.x.protobuf.Bug11.C parseFrom(byte[] data, int offset, int length) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
return parseFrom(data, cursor);
}
public static com.x.protobuf.Bug11.C parseFrom(byte[] data, CurrentCursor cursor) throws java.io.IOException {
com.x.protobuf.Bug11.C message = new com.x.protobuf.Bug11.C();
while(true) {
if (ProtobufInputStream.isAtEnd(data, cursor)) {
return message;
}
int varint = ProtobufInputStream.readRawVarint32(data, cursor);
int tag = ProtobufInputStream.getTagFieldNumber(varint);
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(varint, data, cursor);
 break;
case 1: 
message.setVal(ProtobufInputStream.readString(data,cursor));
break;
}
}
}
public static com.x.protobuf.Bug11.C parseFrom(java.io.InputStream is) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
return parseFrom(is, cursor);
}
public static com.x.protobuf.Bug11.C parseFrom(java.io.InputStream is, int offset, int length) throws java.io.IOException {
CurrentCursor cursor = new CurrentCursor();
cursor.addToPosition(offset);
cursor.setProcessUpToPosition(offset + length);
return parseFrom(is, cursor);
}
public static com.x.protobuf.Bug11.C parseFrom(java.io.InputStream is, CurrentCursor cursor) throws java.io.IOException {
com.x.protobuf.Bug11.C message = new com.x.protobuf.Bug11.C();
while(true) {
if( cursor.getCurrentPosition() == cursor.getProcessUpToPosition() ) {
return message;
}
int varint = ProtobufInputStream.readRawVarint32(is, cursor);
int tag = ProtobufInputStream.getTagFieldNumber(varint);
if (ProtobufInputStream.isAtEnd(cursor)) {
return message;
}
switch(tag) {
case 0: 
return message;
 default: 
 ProtobufInputStream.skipUnknown(varint, is, cursor);
 break;case 1: 
message.setVal(ProtobufInputStream.readString(is,cursor));
break;
}
}
}
}
}

