// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/bug7-google.proto

package com.x.protobuf;

public final class Bug7Google {
	private Bug7Google() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static final class SearchResponse extends com.google.protobuf.GeneratedMessageLite {
		// Use SearchResponse.newBuilder() to construct.
		private SearchResponse() {
			initFields();
		}

		private SearchResponse(boolean noInit) {
		}

		private static final SearchResponse defaultInstance;

		public static SearchResponse getDefaultInstance() {
			return defaultInstance;
		}

		public SearchResponse getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final class Result extends com.google.protobuf.GeneratedMessageLite {
			// Use Result.newBuilder() to construct.
			private Result() {
				initFields();
			}

			private Result(boolean noInit) {
			}

			private static final Result defaultInstance;

			public static Result getDefaultInstance() {
				return defaultInstance;
			}

			public Result getDefaultInstanceForType() {
				return defaultInstance;
			}

			// required string url = 2;
			public static final int URL_FIELD_NUMBER = 2;
			private boolean hasUrl;
			private java.lang.String url_ = "";

			public boolean hasUrl() {
				return hasUrl;
			}

			public java.lang.String getUrl() {
				return url_;
			}

			// optional string title = 3;
			public static final int TITLE_FIELD_NUMBER = 3;
			private boolean hasTitle;
			private java.lang.String title_ = "";

			public boolean hasTitle() {
				return hasTitle;
			}

			public java.lang.String getTitle() {
				return title_;
			}

			// repeated string snippets = 4;
			public static final int SNIPPETS_FIELD_NUMBER = 4;
			private java.util.List<java.lang.String> snippets_ = java.util.Collections.emptyList();

			public java.util.List<java.lang.String> getSnippetsList() {
				return snippets_;
			}

			public int getSnippetsCount() {
				return snippets_.size();
			}

			public java.lang.String getSnippets(int index) {
				return snippets_.get(index);
			}

			private void initFields() {
			}

			public final boolean isInitialized() {
				if (!hasUrl)
					return false;
				return true;
			}

			public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
				getSerializedSize();
				if (hasUrl()) {
					output.writeString(2, getUrl());
				}
				if (hasTitle()) {
					output.writeString(3, getTitle());
				}
				for (java.lang.String element : getSnippetsList()) {
					output.writeString(4, element);
				}
			}

			private int memoizedSerializedSize = -1;

			public int getSerializedSize() {
				int size = memoizedSerializedSize;
				if (size != -1)
					return size;

				size = 0;
				if (hasUrl()) {
					size += com.google.protobuf.CodedOutputStream.computeStringSize(2, getUrl());
				}
				if (hasTitle()) {
					size += com.google.protobuf.CodedOutputStream.computeStringSize(3, getTitle());
				}
				{
					int dataSize = 0;
					for (java.lang.String element : getSnippetsList()) {
						dataSize += com.google.protobuf.CodedOutputStream.computeStringSizeNoTag(element);
					}
					size += dataSize;
					size += 1 * getSnippetsList().size();
				}
				memoizedSerializedSize = size;
				return size;
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Result parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Result parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Result parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Result parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Result parseFrom(java.io.InputStream input) throws java.io.IOException {
				return newBuilder().mergeFrom(input).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Result parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Result parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
				Builder builder = newBuilder();
				if (builder.mergeDelimitedFrom(input)) {
					return builder.buildParsed();
				} else {
					return null;
				}
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Result parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				Builder builder = newBuilder();
				if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
					return builder.buildParsed();
				} else {
					return null;
				}
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Result parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
				return newBuilder().mergeFrom(input).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Result parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
			}

			public static Builder newBuilder() {
				return Builder.create();
			}

			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder(com.x.protobuf.Bug7Google.SearchResponse.Result prototype) {
				return newBuilder().mergeFrom(prototype);
			}

			public Builder toBuilder() {
				return newBuilder(this);
			}

			public static final class Builder extends com.google.protobuf.GeneratedMessageLite.Builder<com.x.protobuf.Bug7Google.SearchResponse.Result, Builder> {
				private com.x.protobuf.Bug7Google.SearchResponse.Result result;

				// Construct using
				// com.x.protobuf.Bug7Google.SearchResponse.Result.newBuilder()
				private Builder() {
				}

				private static Builder create() {
					Builder builder = new Builder();
					builder.result = new com.x.protobuf.Bug7Google.SearchResponse.Result();
					return builder;
				}

				protected com.x.protobuf.Bug7Google.SearchResponse.Result internalGetResult() {
					return result;
				}

				public Builder clear() {
					if (result == null) {
						throw new IllegalStateException("Cannot call clear() after build().");
					}
					result = new com.x.protobuf.Bug7Google.SearchResponse.Result();
					return this;
				}

				public Builder clone() {
					return create().mergeFrom(result);
				}

				public com.x.protobuf.Bug7Google.SearchResponse.Result getDefaultInstanceForType() {
					return com.x.protobuf.Bug7Google.SearchResponse.Result.getDefaultInstance();
				}

				public boolean isInitialized() {
					return result.isInitialized();
				}

				public com.x.protobuf.Bug7Google.SearchResponse.Result build() {
					if (result != null && !isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return buildPartial();
				}

				private com.x.protobuf.Bug7Google.SearchResponse.Result buildParsed() throws com.google.protobuf.InvalidProtocolBufferException {
					if (!isInitialized()) {
						throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
					}
					return buildPartial();
				}

				public com.x.protobuf.Bug7Google.SearchResponse.Result buildPartial() {
					if (result == null) {
						throw new IllegalStateException("build() has already been called on this Builder.");
					}
					if (result.snippets_ != java.util.Collections.EMPTY_LIST) {
						result.snippets_ = java.util.Collections.unmodifiableList(result.snippets_);
					}
					com.x.protobuf.Bug7Google.SearchResponse.Result returnMe = result;
					result = null;
					return returnMe;
				}

				public Builder mergeFrom(com.x.protobuf.Bug7Google.SearchResponse.Result other) {
					if (other == com.x.protobuf.Bug7Google.SearchResponse.Result.getDefaultInstance())
						return this;
					if (other.hasUrl()) {
						setUrl(other.getUrl());
					}
					if (other.hasTitle()) {
						setTitle(other.getTitle());
					}
					if (!other.snippets_.isEmpty()) {
						if (result.snippets_.isEmpty()) {
							result.snippets_ = new java.util.ArrayList<java.lang.String>();
						}
						result.snippets_.addAll(other.snippets_);
					}
					return this;
				}

				public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
					while (true) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							return this;
						default: {
							if (!parseUnknownField(input, extensionRegistry, tag)) {
								return this;
							}
							break;
						}
						case 18: {
							setUrl(input.readString());
							break;
						}
						case 26: {
							setTitle(input.readString());
							break;
						}
						case 34: {
							addSnippets(input.readString());
							break;
						}
						}
					}
				}

				// required string url = 2;
				public boolean hasUrl() {
					return result.hasUrl();
				}

				public java.lang.String getUrl() {
					return result.getUrl();
				}

				public Builder setUrl(java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					result.hasUrl = true;
					result.url_ = value;
					return this;
				}

				public Builder clearUrl() {
					result.hasUrl = false;
					result.url_ = getDefaultInstance().getUrl();
					return this;
				}

				// optional string title = 3;
				public boolean hasTitle() {
					return result.hasTitle();
				}

				public java.lang.String getTitle() {
					return result.getTitle();
				}

				public Builder setTitle(java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					result.hasTitle = true;
					result.title_ = value;
					return this;
				}

				public Builder clearTitle() {
					result.hasTitle = false;
					result.title_ = getDefaultInstance().getTitle();
					return this;
				}

				// repeated string snippets = 4;
				public java.util.List<java.lang.String> getSnippetsList() {
					return java.util.Collections.unmodifiableList(result.snippets_);
				}

				public int getSnippetsCount() {
					return result.getSnippetsCount();
				}

				public java.lang.String getSnippets(int index) {
					return result.getSnippets(index);
				}

				public Builder setSnippets(int index, java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					result.snippets_.set(index, value);
					return this;
				}

				public Builder addSnippets(java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					if (result.snippets_.isEmpty()) {
						result.snippets_ = new java.util.ArrayList<java.lang.String>();
					}
					result.snippets_.add(value);
					return this;
				}

				public Builder addAllSnippets(java.lang.Iterable<? extends java.lang.String> values) {
					if (result.snippets_.isEmpty()) {
						result.snippets_ = new java.util.ArrayList<java.lang.String>();
					}
					super.addAll(values, result.snippets_);
					return this;
				}

				public Builder clearSnippets() {
					result.snippets_ = java.util.Collections.emptyList();
					return this;
				}

				// @@protoc_insertion_point(builder_scope:sync_pb.SearchResponse.Result)
			}

			static {
				defaultInstance = new Result(true);
				com.x.protobuf.Bug7Google.internalForceInit();
				defaultInstance.initFields();
			}

			// @@protoc_insertion_point(class_scope:sync_pb.SearchResponse.Result)
		}

		public static final class Test extends com.google.protobuf.GeneratedMessageLite {
			// Use Test.newBuilder() to construct.
			private Test() {
				initFields();
			}

			private Test(boolean noInit) {
			}

			private static final Test defaultInstance;

			public static Test getDefaultInstance() {
				return defaultInstance;
			}

			public Test getDefaultInstanceForType() {
				return defaultInstance;
			}

			// required string test = 1;
			public static final int TEST_FIELD_NUMBER = 1;
			private boolean hasTest;
			private java.lang.String test_ = "";

			public boolean hasTest() {
				return hasTest;
			}

			public java.lang.String getTest() {
				return test_;
			}

			private void initFields() {
			}

			public final boolean isInitialized() {
				if (!hasTest)
					return false;
				return true;
			}

			public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
				getSerializedSize();
				if (hasTest()) {
					output.writeString(1, getTest());
				}
			}

			private int memoizedSerializedSize = -1;

			public int getSerializedSize() {
				int size = memoizedSerializedSize;
				if (size != -1)
					return size;

				size = 0;
				if (hasTest()) {
					size += com.google.protobuf.CodedOutputStream.computeStringSize(1, getTest());
				}
				memoizedSerializedSize = size;
				return size;
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test parseFrom(java.io.InputStream input) throws java.io.IOException {
				return newBuilder().mergeFrom(input).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
				Builder builder = newBuilder();
				if (builder.mergeDelimitedFrom(input)) {
					return builder.buildParsed();
				} else {
					return null;
				}
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				Builder builder = newBuilder();
				if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
					return builder.buildParsed();
				} else {
					return null;
				}
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
				return newBuilder().mergeFrom(input).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
			}

			public static Builder newBuilder() {
				return Builder.create();
			}

			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder(com.x.protobuf.Bug7Google.SearchResponse.Test prototype) {
				return newBuilder().mergeFrom(prototype);
			}

			public Builder toBuilder() {
				return newBuilder(this);
			}

			public static final class Builder extends com.google.protobuf.GeneratedMessageLite.Builder<com.x.protobuf.Bug7Google.SearchResponse.Test, Builder> {
				private com.x.protobuf.Bug7Google.SearchResponse.Test result;

				// Construct using
				// com.x.protobuf.Bug7Google.SearchResponse.Test.newBuilder()
				private Builder() {
				}

				private static Builder create() {
					Builder builder = new Builder();
					builder.result = new com.x.protobuf.Bug7Google.SearchResponse.Test();
					return builder;
				}

				protected com.x.protobuf.Bug7Google.SearchResponse.Test internalGetResult() {
					return result;
				}

				public Builder clear() {
					if (result == null) {
						throw new IllegalStateException("Cannot call clear() after build().");
					}
					result = new com.x.protobuf.Bug7Google.SearchResponse.Test();
					return this;
				}

				public Builder clone() {
					return create().mergeFrom(result);
				}

				public com.x.protobuf.Bug7Google.SearchResponse.Test getDefaultInstanceForType() {
					return com.x.protobuf.Bug7Google.SearchResponse.Test.getDefaultInstance();
				}

				public boolean isInitialized() {
					return result.isInitialized();
				}

				public com.x.protobuf.Bug7Google.SearchResponse.Test build() {
					if (result != null && !isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return buildPartial();
				}

				private com.x.protobuf.Bug7Google.SearchResponse.Test buildParsed() throws com.google.protobuf.InvalidProtocolBufferException {
					if (!isInitialized()) {
						throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
					}
					return buildPartial();
				}

				public com.x.protobuf.Bug7Google.SearchResponse.Test buildPartial() {
					if (result == null) {
						throw new IllegalStateException("build() has already been called on this Builder.");
					}
					com.x.protobuf.Bug7Google.SearchResponse.Test returnMe = result;
					result = null;
					return returnMe;
				}

				public Builder mergeFrom(com.x.protobuf.Bug7Google.SearchResponse.Test other) {
					if (other == com.x.protobuf.Bug7Google.SearchResponse.Test.getDefaultInstance())
						return this;
					if (other.hasTest()) {
						setTest(other.getTest());
					}
					return this;
				}

				public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
					while (true) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							return this;
						default: {
							if (!parseUnknownField(input, extensionRegistry, tag)) {
								return this;
							}
							break;
						}
						case 10: {
							setTest(input.readString());
							break;
						}
						}
					}
				}

				// required string test = 1;
				public boolean hasTest() {
					return result.hasTest();
				}

				public java.lang.String getTest() {
					return result.getTest();
				}

				public Builder setTest(java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					result.hasTest = true;
					result.test_ = value;
					return this;
				}

				public Builder clearTest() {
					result.hasTest = false;
					result.test_ = getDefaultInstance().getTest();
					return this;
				}

				// @@protoc_insertion_point(builder_scope:sync_pb.SearchResponse.Test)
			}

			static {
				defaultInstance = new Test(true);
				com.x.protobuf.Bug7Google.internalForceInit();
				defaultInstance.initFields();
			}

			// @@protoc_insertion_point(class_scope:sync_pb.SearchResponse.Test)
		}

		public static final class Test2 extends com.google.protobuf.GeneratedMessageLite {
			// Use Test2.newBuilder() to construct.
			private Test2() {
				initFields();
			}

			private Test2(boolean noInit) {
			}

			private static final Test2 defaultInstance;

			public static Test2 getDefaultInstance() {
				return defaultInstance;
			}

			public Test2 getDefaultInstanceForType() {
				return defaultInstance;
			}

			// optional int32 test = 1;
			public static final int TEST_FIELD_NUMBER = 1;
			private boolean hasTest;
			private int test_ = 0;

			public boolean hasTest() {
				return hasTest;
			}

			public int getTest() {
				return test_;
			}

			private void initFields() {
			}

			public final boolean isInitialized() {
				return true;
			}

			public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
				getSerializedSize();
				if (hasTest()) {
					output.writeInt32(1, getTest());
				}
			}

			private int memoizedSerializedSize = -1;

			public int getSerializedSize() {
				int size = memoizedSerializedSize;
				if (size != -1)
					return size;

				size = 0;
				if (hasTest()) {
					size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, getTest());
				}
				memoizedSerializedSize = size;
				return size;
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test2 parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test2 parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test2 parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test2 parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test2 parseFrom(java.io.InputStream input) throws java.io.IOException {
				return newBuilder().mergeFrom(input).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test2 parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test2 parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
				Builder builder = newBuilder();
				if (builder.mergeDelimitedFrom(input)) {
					return builder.buildParsed();
				} else {
					return null;
				}
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test2 parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				Builder builder = newBuilder();
				if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
					return builder.buildParsed();
				} else {
					return null;
				}
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test2 parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
				return newBuilder().mergeFrom(input).buildParsed();
			}

			public static com.x.protobuf.Bug7Google.SearchResponse.Test2 parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
			}

			public static Builder newBuilder() {
				return Builder.create();
			}

			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder(com.x.protobuf.Bug7Google.SearchResponse.Test2 prototype) {
				return newBuilder().mergeFrom(prototype);
			}

			public Builder toBuilder() {
				return newBuilder(this);
			}

			public static final class Builder extends com.google.protobuf.GeneratedMessageLite.Builder<com.x.protobuf.Bug7Google.SearchResponse.Test2, Builder> {
				private com.x.protobuf.Bug7Google.SearchResponse.Test2 result;

				// Construct using
				// com.x.protobuf.Bug7Google.SearchResponse.Test2.newBuilder()
				private Builder() {
				}

				private static Builder create() {
					Builder builder = new Builder();
					builder.result = new com.x.protobuf.Bug7Google.SearchResponse.Test2();
					return builder;
				}

				protected com.x.protobuf.Bug7Google.SearchResponse.Test2 internalGetResult() {
					return result;
				}

				public Builder clear() {
					if (result == null) {
						throw new IllegalStateException("Cannot call clear() after build().");
					}
					result = new com.x.protobuf.Bug7Google.SearchResponse.Test2();
					return this;
				}

				public Builder clone() {
					return create().mergeFrom(result);
				}

				public com.x.protobuf.Bug7Google.SearchResponse.Test2 getDefaultInstanceForType() {
					return com.x.protobuf.Bug7Google.SearchResponse.Test2.getDefaultInstance();
				}

				public boolean isInitialized() {
					return result.isInitialized();
				}

				public com.x.protobuf.Bug7Google.SearchResponse.Test2 build() {
					if (result != null && !isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return buildPartial();
				}

				private com.x.protobuf.Bug7Google.SearchResponse.Test2 buildParsed() throws com.google.protobuf.InvalidProtocolBufferException {
					if (!isInitialized()) {
						throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
					}
					return buildPartial();
				}

				public com.x.protobuf.Bug7Google.SearchResponse.Test2 buildPartial() {
					if (result == null) {
						throw new IllegalStateException("build() has already been called on this Builder.");
					}
					com.x.protobuf.Bug7Google.SearchResponse.Test2 returnMe = result;
					result = null;
					return returnMe;
				}

				public Builder mergeFrom(com.x.protobuf.Bug7Google.SearchResponse.Test2 other) {
					if (other == com.x.protobuf.Bug7Google.SearchResponse.Test2.getDefaultInstance())
						return this;
					if (other.hasTest()) {
						setTest(other.getTest());
					}
					return this;
				}

				public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
					while (true) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							return this;
						default: {
							if (!parseUnknownField(input, extensionRegistry, tag)) {
								return this;
							}
							break;
						}
						case 8: {
							setTest(input.readInt32());
							break;
						}
						}
					}
				}

				// optional int32 test = 1;
				public boolean hasTest() {
					return result.hasTest();
				}

				public int getTest() {
					return result.getTest();
				}

				public Builder setTest(int value) {
					result.hasTest = true;
					result.test_ = value;
					return this;
				}

				public Builder clearTest() {
					result.hasTest = false;
					result.test_ = 0;
					return this;
				}

				// @@protoc_insertion_point(builder_scope:sync_pb.SearchResponse.Test2)
			}

			static {
				defaultInstance = new Test2(true);
				com.x.protobuf.Bug7Google.internalForceInit();
				defaultInstance.initFields();
			}

			// @@protoc_insertion_point(class_scope:sync_pb.SearchResponse.Test2)
		}

		// repeated group Result = 1 {
		public static final int RESULT_FIELD_NUMBER = 1;
		private java.util.List<com.x.protobuf.Bug7Google.SearchResponse.Result> result_ = java.util.Collections.emptyList();

		public java.util.List<com.x.protobuf.Bug7Google.SearchResponse.Result> getResultList() {
			return result_;
		}

		public int getResultCount() {
			return result_.size();
		}

		public com.x.protobuf.Bug7Google.SearchResponse.Result getResult(int index) {
			return result_.get(index);
		}

		// optional group Test = 2 {
		public static final int TEST_FIELD_NUMBER = 2;
		private boolean hasTest;
		private com.x.protobuf.Bug7Google.SearchResponse.Test test_;

		public boolean hasTest() {
			return hasTest;
		}

		public com.x.protobuf.Bug7Google.SearchResponse.Test getTest() {
			return test_;
		}

		// required group Test2 = 3 {
		public static final int TEST2_FIELD_NUMBER = 3;
		private boolean hasTest2;
		private com.x.protobuf.Bug7Google.SearchResponse.Test2 test2_;

		public boolean hasTest2() {
			return hasTest2;
		}

		public com.x.protobuf.Bug7Google.SearchResponse.Test2 getTest2() {
			return test2_;
		}

		private void initFields() {
			test_ = com.x.protobuf.Bug7Google.SearchResponse.Test.getDefaultInstance();
			test2_ = com.x.protobuf.Bug7Google.SearchResponse.Test2.getDefaultInstance();
		}

		public final boolean isInitialized() {
			if (!hasTest2)
				return false;
			for (com.x.protobuf.Bug7Google.SearchResponse.Result element : getResultList()) {
				if (!element.isInitialized())
					return false;
			}
			if (hasTest()) {
				if (!getTest().isInitialized())
					return false;
			}
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			for (com.x.protobuf.Bug7Google.SearchResponse.Result element : getResultList()) {
				output.writeGroup(1, element);
			}
			if (hasTest()) {
				output.writeGroup(2, getTest());
			}
			if (hasTest2()) {
				output.writeGroup(3, getTest2());
			}
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (com.x.protobuf.Bug7Google.SearchResponse.Result element : getResultList()) {
				size += com.google.protobuf.CodedOutputStream.computeGroupSize(1, element);
			}
			if (hasTest()) {
				size += com.google.protobuf.CodedOutputStream.computeGroupSize(2, getTest());
			}
			if (hasTest2()) {
				size += com.google.protobuf.CodedOutputStream.computeGroupSize(3, getTest2());
			}
			memoizedSerializedSize = size;
			return size;
		}

		public static com.x.protobuf.Bug7Google.SearchResponse parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.x.protobuf.Bug7Google.SearchResponse parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static com.x.protobuf.Bug7Google.SearchResponse parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.x.protobuf.Bug7Google.SearchResponse parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static com.x.protobuf.Bug7Google.SearchResponse parseFrom(java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.x.protobuf.Bug7Google.SearchResponse parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static com.x.protobuf.Bug7Google.SearchResponse parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.x.protobuf.Bug7Google.SearchResponse parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.x.protobuf.Bug7Google.SearchResponse parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.x.protobuf.Bug7Google.SearchResponse parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(com.x.protobuf.Bug7Google.SearchResponse prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		public static final class Builder extends com.google.protobuf.GeneratedMessageLite.Builder<com.x.protobuf.Bug7Google.SearchResponse, Builder> {
			private com.x.protobuf.Bug7Google.SearchResponse result;

			// Construct using
			// com.x.protobuf.Bug7Google.SearchResponse.newBuilder()
			private Builder() {
			}

			private static Builder create() {
				Builder builder = new Builder();
				builder.result = new com.x.protobuf.Bug7Google.SearchResponse();
				return builder;
			}

			protected com.x.protobuf.Bug7Google.SearchResponse internalGetResult() {
				return result;
			}

			public Builder clear() {
				if (result == null) {
					throw new IllegalStateException("Cannot call clear() after build().");
				}
				result = new com.x.protobuf.Bug7Google.SearchResponse();
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(result);
			}

			public com.x.protobuf.Bug7Google.SearchResponse getDefaultInstanceForType() {
				return com.x.protobuf.Bug7Google.SearchResponse.getDefaultInstance();
			}

			public boolean isInitialized() {
				return result.isInitialized();
			}

			public com.x.protobuf.Bug7Google.SearchResponse build() {
				if (result != null && !isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return buildPartial();
			}

			private com.x.protobuf.Bug7Google.SearchResponse buildParsed() throws com.google.protobuf.InvalidProtocolBufferException {
				if (!isInitialized()) {
					throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
				}
				return buildPartial();
			}

			public com.x.protobuf.Bug7Google.SearchResponse buildPartial() {
				if (result == null) {
					throw new IllegalStateException("build() has already been called on this Builder.");
				}
				if (result.result_ != java.util.Collections.EMPTY_LIST) {
					result.result_ = java.util.Collections.unmodifiableList(result.result_);
				}
				com.x.protobuf.Bug7Google.SearchResponse returnMe = result;
				result = null;
				return returnMe;
			}

			public Builder mergeFrom(com.x.protobuf.Bug7Google.SearchResponse other) {
				if (other == com.x.protobuf.Bug7Google.SearchResponse.getDefaultInstance())
					return this;
				if (!other.result_.isEmpty()) {
					if (result.result_.isEmpty()) {
						result.result_ = new java.util.ArrayList<com.x.protobuf.Bug7Google.SearchResponse.Result>();
					}
					result.result_.addAll(other.result_);
				}
				if (other.hasTest()) {
					mergeTest(other.getTest());
				}
				if (other.hasTest2()) {
					mergeTest2(other.getTest2());
				}
				return this;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						return this;
					default: {
						if (!parseUnknownField(input, extensionRegistry, tag)) {
							return this;
						}
						break;
					}
					case 11: {
						com.x.protobuf.Bug7Google.SearchResponse.Result.Builder subBuilder = com.x.protobuf.Bug7Google.SearchResponse.Result.newBuilder();
						input.readGroup(1, subBuilder, extensionRegistry);
						addResult(subBuilder.buildPartial());
						break;
					}
					case 19: {
						com.x.protobuf.Bug7Google.SearchResponse.Test.Builder subBuilder = com.x.protobuf.Bug7Google.SearchResponse.Test.newBuilder();
						if (hasTest()) {
							subBuilder.mergeFrom(getTest());
						}
						input.readGroup(2, subBuilder, extensionRegistry);
						setTest(subBuilder.buildPartial());
						break;
					}
					case 27: {
						com.x.protobuf.Bug7Google.SearchResponse.Test2.Builder subBuilder = com.x.protobuf.Bug7Google.SearchResponse.Test2.newBuilder();
						if (hasTest2()) {
							subBuilder.mergeFrom(getTest2());
						}
						input.readGroup(3, subBuilder, extensionRegistry);
						setTest2(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			// repeated group Result = 1 {
			public java.util.List<com.x.protobuf.Bug7Google.SearchResponse.Result> getResultList() {
				return java.util.Collections.unmodifiableList(result.result_);
			}

			public int getResultCount() {
				return result.getResultCount();
			}

			public com.x.protobuf.Bug7Google.SearchResponse.Result getResult(int index) {
				return result.getResult(index);
			}

			public Builder setResult(int index, com.x.protobuf.Bug7Google.SearchResponse.Result value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.result_.set(index, value);
				return this;
			}

			public Builder setResult(int index, com.x.protobuf.Bug7Google.SearchResponse.Result.Builder builderForValue) {
				result.result_.set(index, builderForValue.build());
				return this;
			}

			public Builder addResult(com.x.protobuf.Bug7Google.SearchResponse.Result value) {
				if (value == null) {
					throw new NullPointerException();
				}
				if (result.result_.isEmpty()) {
					result.result_ = new java.util.ArrayList<com.x.protobuf.Bug7Google.SearchResponse.Result>();
				}
				result.result_.add(value);
				return this;
			}

			public Builder addResult(com.x.protobuf.Bug7Google.SearchResponse.Result.Builder builderForValue) {
				if (result.result_.isEmpty()) {
					result.result_ = new java.util.ArrayList<com.x.protobuf.Bug7Google.SearchResponse.Result>();
				}
				result.result_.add(builderForValue.build());
				return this;
			}

			public Builder addAllResult(java.lang.Iterable<? extends com.x.protobuf.Bug7Google.SearchResponse.Result> values) {
				if (result.result_.isEmpty()) {
					result.result_ = new java.util.ArrayList<com.x.protobuf.Bug7Google.SearchResponse.Result>();
				}
				super.addAll(values, result.result_);
				return this;
			}

			public Builder clearResult() {
				result.result_ = java.util.Collections.emptyList();
				return this;
			}

			// optional group Test = 2 {
			public boolean hasTest() {
				return result.hasTest();
			}

			public com.x.protobuf.Bug7Google.SearchResponse.Test getTest() {
				return result.getTest();
			}

			public Builder setTest(com.x.protobuf.Bug7Google.SearchResponse.Test value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasTest = true;
				result.test_ = value;
				return this;
			}

			public Builder setTest(com.x.protobuf.Bug7Google.SearchResponse.Test.Builder builderForValue) {
				result.hasTest = true;
				result.test_ = builderForValue.build();
				return this;
			}

			public Builder mergeTest(com.x.protobuf.Bug7Google.SearchResponse.Test value) {
				if (result.hasTest() && result.test_ != com.x.protobuf.Bug7Google.SearchResponse.Test.getDefaultInstance()) {
					result.test_ = com.x.protobuf.Bug7Google.SearchResponse.Test.newBuilder(result.test_).mergeFrom(value).buildPartial();
				} else {
					result.test_ = value;
				}
				result.hasTest = true;
				return this;
			}

			public Builder clearTest() {
				result.hasTest = false;
				result.test_ = com.x.protobuf.Bug7Google.SearchResponse.Test.getDefaultInstance();
				return this;
			}

			// required group Test2 = 3 {
			public boolean hasTest2() {
				return result.hasTest2();
			}

			public com.x.protobuf.Bug7Google.SearchResponse.Test2 getTest2() {
				return result.getTest2();
			}

			public Builder setTest2(com.x.protobuf.Bug7Google.SearchResponse.Test2 value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasTest2 = true;
				result.test2_ = value;
				return this;
			}

			public Builder setTest2(com.x.protobuf.Bug7Google.SearchResponse.Test2.Builder builderForValue) {
				result.hasTest2 = true;
				result.test2_ = builderForValue.build();
				return this;
			}

			public Builder mergeTest2(com.x.protobuf.Bug7Google.SearchResponse.Test2 value) {
				if (result.hasTest2() && result.test2_ != com.x.protobuf.Bug7Google.SearchResponse.Test2.getDefaultInstance()) {
					result.test2_ = com.x.protobuf.Bug7Google.SearchResponse.Test2.newBuilder(result.test2_).mergeFrom(value).buildPartial();
				} else {
					result.test2_ = value;
				}
				result.hasTest2 = true;
				return this;
			}

			public Builder clearTest2() {
				result.hasTest2 = false;
				result.test2_ = com.x.protobuf.Bug7Google.SearchResponse.Test2.getDefaultInstance();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:sync_pb.SearchResponse)
		}

		static {
			defaultInstance = new SearchResponse(true);
			com.x.protobuf.Bug7Google.internalForceInit();
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:sync_pb.SearchResponse)
	}

	static {
	}

	public static void internalForceInit() {
	}

	// @@protoc_insertion_point(outer_class_scope)
}
